name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install valgrind and dependencie for 32 bits compilation
      run: sudo apt update && sudo apt install libc6-dev-i386 valgrind -y
    
    - name: Run test rule, clone the tester and run the tests
      run: make run_test

    - name: clean
      run: make fclean