name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install valgrind and dependencie for 32 bits compilation
      run: sudo apt update && sudo apt install libc6-dev-i386 valgrind -y
    
    - name: Run make
      run: make

    - name: Run basic diff tests
      run: make dtest vtest

    - name: Run valgrind tests
      run: make vtest

    - name: Run valgrind tests bonus -p
      run: make vtest_p

    - name: Run valgrind tests bonus -r
      run: make vtest_r

    - name: clean
      run: make fclean
