name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install valgrind and dependencie for 32 bits compilation
      run: sudo apt update && sudo apt install libc6-dev-i386 valgrind -y
    
        #- name: Run make
        #run: make

        #- name: Run basic diff tests
        #run: make dtest
        
        # - name: Call tester all test
        #run: make all_test
    - name: Clone tester
      run: git clone https://github.com/Ycaro02/ft_nmTester.git

    - name: Run basic test
      run : ./ft_nmTester/call_tester.sh 0

    - name: Run valgrind basic test
      run : ./ft_nmTester/call_tester.sh 1

    - name: Run bonus test
      run : ./ft_nmTester/call_tester.sh 0 1

    - name: Run valgrind bonus test
      run : ./ft_nmTester/call_tester.sh 1 1

    - name: clean
      run: make fclean